import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import { motion as m } from 'framer-motion';

import formImage from '../public/form.png';

export default function Home() {
  const router = useRouter();

  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'United States',
      terms: '',
    },

    // Validate form
    validationSchema: Yup.object().shape({
      name: Yup.string()
        .min(2, 'Name must be a minimum of 2 characters')
        .max(50, 'Name must be 50 characters or less')
        .required('Required'),
      email: Yup.string().email('Invalid email address').required('Required'),
      terms: Yup.array().required('Terms of service is required'),
    }),

    // Submit form
    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: '/success', query: values });
    },
  });

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className='absolute w-full'
    >
      <Head>
        <title>E-learning Form</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container px-6 mx-auto'>
        <section className='flex items-center justify-center h-screen'>
          <form
            onSubmit={formik.handleSubmit}
            className='flex font-latoRegular bg-white rounded-md shadow-xl overflow-hidden'
          >
            <div className='flex-1 text-gray-700 p-10'>
              <h1 className='text-3xl font-latoBold pb-2'>
                Let&apos;s get started👋
              </h1>
              <p className='md:text-lg text-gray-500'>
                Join our E-learning platform today and unlock over 500+ courses
                and digital assets ready to download.
              </p>

              <div className='mt-6'>
                <div className='mb-1'>
                  <label
                    htmlFor='name'
                    className="inline-block font-latoBold text-sm mb-1 after:content-['*'] after:ml-0.5 after:text-red-500"
                  >
                    Name
                  </label>
                  <input
                    type='text'
                    id='name'
                    name='name'
                    placeholder='Enter your name'
                    className={`block p-2 w-full border border-solid border-gray-500 rounded-md transition duration-300 ease-in-out ${
                      formik.touched.name && formik.errors.name
                        ? ' border border-solid border-red-500 ring-2 ring-red-500 focus:border-red-500 focus:ring-2 focus:ring-red-500'
                        : 'focus:border-teal-500 focus:ring-2 focus:ring-teal-500'
                    }`}
                    aria-describedby='nameHelpBlock'
                    value={formik.values.name}
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  />
                  <p
                    id='nameHelpBlock'
                    className='h-6 mt-1 text-sm font-latoRegular text-red-500'
                  >
                    {formik.touched.name && formik.errors.name ? (
                      <span className='flex items-center justify-end'>
                        {formik.errors.name}
                        <svg
                          xmlns='http://www.w3.org/2000/svg'
                          fill='none'
                          viewBox='0 0 24 24'
                          strokeWidth={1.5}
                          stroke='currentColor'
                          className='w-6 h-6 ml-2 text-red-500'
                        >
                          <path
                            strokeLinecap='round'
                            strokeLinejoin='round'
                            d='M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z'
                          />
                        </svg>
                      </span>
                    ) : (
                      ''
                    )}
                  </p>
                </div>

                <div className='mb-1'>
                  <label
                    htmlFor='email'
                    className="inline-block font-latoBold text-sm mb-1 after:content-['*'] after:ml-0.5 after:text-red-500"
                  >
                    Email
                  </label>
                  <input
                    type='email'
                    id='email'
                    name='email'
                    aria-describedby='emailHelpBlock'
                    placeholder='Enter your email address'
                    className={`block p-2 w-full border border-solid border-gray-500 rounded-md transition duration-300 ease-in-out ${
                      formik.touched.email && formik.errors.email
                        ? ' border border-solid border-red-500 ring-2 ring-red-500 focus:border-red-500 focus:ring-2 focus:ring-red-500'
                        : 'focus:border-teal-500 focus:ring-2 focus:ring-teal-500'
                    }`}
                    value={formik.values.email}
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  />
                  <p
                    id='emailHelpBlock'
                    className='h-6 mt-1 text-sm font-latoRegular text-red-500'
                  >
                    {formik.touched.email && formik.errors.email ? (
                      <span className='flex items-center justify-end'>
                        {formik.errors.email}
                        <svg
                          xmlns='http://www.w3.org/2000/svg'
                          fill='none'
                          viewBox='0 0 24 24'
                          strokeWidth={1.5}
                          stroke='currentColor'
                          className='w-6 h-6 ml-2 text-red-500'
                        >
                          <path
                            strokeLinecap='round'
                            strokeLinejoin='round'
                            d='M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z'
                          />
                        </svg>
                      </span>
                    ) : (
                      ''
                    )}
                  </p>
                </div>

                <div className='mb-4'>
                  <label
                    htmlFor='country'
                    className='inline-block font-latoBold text-sm mb-1'
                  >
                    Country
                  </label>
                  <select
                    name='country'
                    id='country'
                    className='block p-2 w-full border border-solid border-gray-500 rounded-md focus:border-teal-500 focus:ring-2 focus:ring-teal-500 transition duration-300 ease-in-out'
                    value={formik.values.country}
                    onChange={formik.handleChange}
                  >
                    <option value='us'>United States</option>
                    <option value='uk'>United Kingdom</option>
                    <option value='germany'>Germany</option>
                    <option value='france'>France</option>
                    <option value='norway'>Norway</option>
                    <option value='switzerland'>Switzerland</option>
                    <option value='spain'>Spain</option>
                    <option value='portugal'>Portugal</option>
                  </select>
                </div>

                <div className='mb-1'>
                  <label
                    htmlFor='terms'
                    className="inline-block font-latoBold text-sm mb-1 after:content-['*'] after:ml-0.5 after:text-red-500"
                  >
                    Terms of Service
                  </label>
                  <div className='flex items-center gap-2'>
                    <input
                      type='checkbox'
                      id='terms'
                      name='terms'
                      aria-describedby='termsHelpBlock'
                      className='h-5 w-5 text-teal-500 focus:border-teal-500 focus:ring-teal-500'
                      value='checked'
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                    />
                    <p className='text-sm font-latoBold text-gray-500'>
                      I agree to the Terms and Services that my data will be
                      taken and sold.🤣
                    </p>
                  </div>
                  <p
                    id='termsHelpBlock'
                    className='h-6 text-sm font-latoRegular text-red-500'
                  >
                    {formik.touched.terms && formik.errors.terms ? (
                      <span className='flex items-center justify-end'>
                        {formik.errors.terms}
                        <svg
                          xmlns='http://www.w3.org/2000/svg'
                          fill='none'
                          viewBox='0 0 24 24'
                          strokeWidth={1.5}
                          stroke='currentColor'
                          className='w-6 h-6 ml-2 text-red-500'
                        >
                          <path
                            strokeLinecap='round'
                            strokeLinejoin='round'
                            d='M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z'
                          />
                        </svg>
                      </span>
                    ) : (
                      ''
                    )}
                  </p>
                </div>

                <button
                  type='submit'
                  className='w-full bg-teal-500 uppercase text-sm text-white font-latoBold mt-2 py-3 px-6 rounded-lg hover:bg-teal-600 focus:bg-teal-600 active:bg-teal-700 transition duration-300 ease-in-out'
                >
                  start learning today!
                </button>
              </div>
            </div>

            <div className='flex-1 relative overflow-hidden hidden lg:block p-10'>
              <Image
                src={formImage}
                fill
                priority
                className='max-w-full h-auto object-cover'
                alt='Bookshelf with books'
              />
            </div>
          </form>
        </section>
      </main>
    </m.div>
  );
}
